version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  version: 2
  main:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master
jobs:
  build-deploy:
    executor:
      name: node/default
      tag: '12.16.1'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run:
          name: Deploying
          command: node ./ftp-deploy.js $FTP_ADDRESS $FTP_USER $FTP_PASSWORD

